name       : libdvdnav
version    : 6.1.0
release    : 6
source     :
    - https://download.videolan.org/pub/videolan/libdvdnav/6.1.0/libdvdnav-6.1.0.tar.bz2 : f697b15ea9f75e9f36bdf6ec3726308169f154e2b1e99865d0bbe823720cee5b
homepage   : https://www.videolan.org/index.htm
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD navigation library
description: |
    libdvdnav is a library that allows easy use of sophisticated DVD navigation features such as DVD menus, multiangle playback and even interactive DVD games.
builddeps  :
    - pkgconfig(dvdread)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
