name        : libdvdnav
version     : 5.0.1
release     : 3
source      :
    - http://download.videolan.org/videolan/libdvdnav/5.0.1/libdvdnav-5.0.1.tar.bz2 : 72b1cb8266f163d4a1481b92c7b6c53e6dc9274d2a6befb08ffc351fe7a4a2a9
homepage    : http://www.videolan.org/index.htm
license     : GPL-2.0
component   : multimedia.library
summary     : DVD navigation library
description : |
    libdvdnav is a library that allows easy use of sophisticated DVD navigation features such as DVD menus, multiangle playback and even interactive DVD games.
builddeps   :
    - pkgconfig(dvdread)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
