name       : libdvdnav
version    : 6.0.1
release    : 5
source     :
    - http://download.videolan.org/pub/videolan/libdvdnav/6.0.1/libdvdnav-6.0.1.tar.bz2 : e566a396f1950017088bfd760395b0565db44234195ada5413366c9d23926733
homepage   : https://www.videolan.org/index.htm
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD navigation library
description: |
    libdvdnav is a library that allows easy use of sophisticated DVD navigation features such as DVD menus, multiangle playback and even interactive DVD games.
builddeps  :
    - pkgconfig(dvdread)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
