name       : libdvdnav
version    : 6.1.1
release    : 8
source     :
    - https://download.videolan.org/pub/videolan/libdvdnav/6.1.1/libdvdnav-6.1.1.tar.bz2 : c191a7475947d323ff7680cf92c0fb1be8237701885f37656c64d04e98d18d48
homepage   : https://www.videolan.org/developers/libdvdnav.html
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : DVD navigation library
description: |
    libdvdnav is a library that allows easy use of sophisticated DVD navigation features such as DVD menus, multiangle playback and even interactive DVD games.
builddeps  :
    - pkgconfig(dvdread)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share
